---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/franklinvillehardware.com
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/python3 -m venv venv
    - cd $DEPLOYPATH && source venv/bin/activate && pip install -r requirements.txt
    - mkdir -p $DEPLOYPATH/tmp && touch $DEPLOYPATH/tmp/restart.txt
