---
deployment:
  tasks:
    - export DEPLOYPATH=/home/franqtqt/repositories/FranklinvilleHardware
    - /bin/cp -R templates $DEPLOYPATH/
    - /bin/cp -R static $DEPLOYPATH/
    - /bin/cp app.py $DEPLOYPATH/
    - /bin/cp passenger_wsgi.py $DEPLOYPATH/
    - /bin/cp requirements.txt $DEPLOYPATH/
    - mkdir -p $DEPLOYPATH/tmp && touch $DEPLOYPATH/tmp/restart.txt
